version: v1
kind: Pod
metadata:
  name: monitoring-proxy
spec:
  containers:
    - name: monitoring-proxy-go-image
      image: gcr.io/chrome_infra_mon_proxy/monitoring_proxy_go_6ac48b2fb7b1
      imagePullPolicy: Always
  restartPolicy: Always
  dnsPolicy: Default
